- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Bagel
  # - Amber # Begin Stellar
  # - Box
  # - Elkridge
  # - Fland
  # - Marathon
  # - Oasis
  # - Packed
  # - Plasma
  # - Reach
  # - Exo
  # - Snowball # End Stellar
