// SPDX-FileCopyrightText: 2025 Janet Blackquill
//
// SPDX-License-Identifier: LicenseRef-Wallening

using System.Linq;
using Content.Stellar.Shared.ResourceBars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Stellar.Client.ResourceBars;

[GenerateTypedNameReferences]
public sealed partial class ResourceBarsUI : UIWidget
{
    private readonly Dictionary<ProtoId<ResourceBarPrototype>, ResourceBarControl> _resourceBars = new();

    public ResourceBarsUI()
    {
        RobustXamlLoader.Load(this);
    }

    public void Clear()
    {
        foreach (var position in Enum.GetValues<ResourceUIPosition>())
        {
            ContainerFor((ResourceUIPosition)position).RemoveAllChildren();
        }
        _resourceBars.Clear();
    }

    private BoxContainer ContainerFor(ResourceUIPosition position) =>
        position switch {
            ResourceUIPosition.Left => LeftContainer,
            ResourceUIPosition.Middle => MiddleContainer,
            ResourceUIPosition.Right => RightContainer,
            _ => throw new ArgumentOutOfRangeException(nameof(position), position, null)
        };

    public void Update(IPrototypeManager prototype, IReadOnlyDictionary<ProtoId<ResourceBarPrototype>, ResourceBarState> bars, IReadOnlyDictionary<ProtoId<ResourceBarCategoryPrototype>, int> collation)
    {
        foreach (var (key, child) in _resourceBars)
        {
            if (bars.ContainsKey(key))
                continue;

            child.Parent?.Children.Remove(child);
            _resourceBars.Remove(key);
        }

        foreach (var (barID, data) in bars)
        {
            if (_resourceBars.TryGetValue(barID, out var existingBar))
            {
                existingBar.Update(data);
                continue;
            }

            var bar = prototype.Index(barID);
            var incomingCollation = collation.GetValueOrDefault(bar.Category, -1);

            var container = ContainerFor(bar.Location);
            var foundOrder = false;
            var newBarControl = new ResourceBarControl(bar, data);
            _resourceBars[barID] = newBarControl;

            foreach (var otherBarControl in container.Children.Cast<ResourceBarControl>())
            {
                var otherBar = prototype.Index(otherBarControl.BarPrototype);
                if (incomingCollation - collation.GetValueOrDefault(otherBar.Category, -1) >= 0)
                    continue;

                container.Children.Add(newBarControl);
                _resourceBars[barID].SetPositionInParent(otherBarControl.GetPositionInParent());
                foundOrder = true;
                break;
            }

            if (!foundOrder)
                container.Children.Add(newBarControl);
        }
    }
}
