# SPDX-FileCopyrightText: 2026 Janet Blackquill
#
# SPDX-License-Identifier: LicenseRef-Wallening

- type: entity
  abstract: true
  id: StellarStructureBase
  placement:
    mode: SnapgridCenter
  components:
  - type: Physics
    bodyType: Static
  - type: Clickable
  - type: Transform
    anchored: true

- type: entity
  abstract: true
  id: StellarStructureMovable
  components:
  - type: Transform
    anchored: true
    noRot: false
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.45,-0.45,0.45,0.45"
        density: 60
        mask:
        - MachineMask
        layer:
        - GlassAirlockLayer
  - type: InteractionOutline
  - type: Anchorable
  - type: GravityAffected
  - type: Pullable

- type: entity
  abstract: true
  id: StellarStructureOccluder
  components:
  - type: BlockWeather
  - type: SunShadowCast
  - type: Occluder
  - type: IsRoof

- type: entity
  abstract: true
  id: StellarStructureWall
  placement:
    mode: SnapgridCenter
    snap:
    - Wall
  components:
  - type: Tag
    tags:
    - Wall
  - type: Appearance
  - type: Sprite
    drawdepth: Walls
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.5,-0.5,0.5,0.5"
        mask:
        - FullTileMask
        layer:
        - WallLayer
        density: 1000
  - type: Airtight
  - type: PlacementReplacement
    key: walls
  - type: RadiationBlocker
    resistance: 2
  - type: CosmicCorruptible
    convertTo: StellarWallMalign
  - type: Icon
    state: full
  - type: Anchorable
    flags: Anchorable
  - type: Rotatable

- type: entity
  abstract: true
  id: StellarStructureWallDamageable
  components:
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 400
      behaviors:
      - !type:DoActsBehavior
        acts: ["Destruction"]
      - !type:PlaySoundBehavior
        sound:
          collection: MetalSlam
    - trigger:
        !type:DamageTrigger
        damage: 200
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: MetalSlam
      - !type:ChangeConstructionNodeBehavior
        node: Girder
      - !type:DoActsBehavior
        acts: ["Destruction"]
  - type: RangedDamageSound
    soundGroups:
      Brute:
        collection:
          MetalBulletImpact
    soundTypes:
      Heat:
        collection:
          MetalLaserImpact
  - type: Damageable
    damageContainer: StructuralInorganic
    damageModifierSet: StructuralMetallic

- type: entity
  abstract: true
  parent: StellarStructureWallDamageable
  id: StellarStructureWallDamageableStrong
  components:
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 600
      behaviors:
      - !type:DoActsBehavior
        acts: ["Destruction"]
      - !type:PlaySoundBehavior
        sound:
          collection: MetalSlam
    - trigger:
        !type:DamageTrigger
        damage: 400
      behaviors:
      - !type:PlaySoundBehavior
        sound:
          collection: MetalSlam
      - !type:ChangeConstructionNodeBehavior
        node: Girder
      - !type:DoActsBehavior
        acts: ["Destruction"]
  - type: Damageable
    damageModifierSet: StructuralMetallicStrong

- type: entity
  abstract: true
  parent:
  - StellarStructureBase
  - StellarStructureOccluder
  - StellarStructureWall
  id: StellarStructureBaseWall

- type: entity
  abstract: true
  id: StellarStructureWallRCDDeconstructible
  components:
  - type: RCDDeconstructable
    cost: 6
    delay: 8
    fx: EffectRCDDeconstruct8
